### ISSUE TITLE
CALM bug? - no output folder after compilation

### ISSUE THREAD

**Issue by zhangyuanlin** [Topology/ALM-Compiler#21]
I don't see the output folder any more after compiling a "good" ALM program. E.g., this program
```
system description test
    theory test
      module test
        sort declarations
            coordinates :: universe
            points :: universe
               attributes
                  x : 1..10
                  y : 1..10

        constant declarations
            p1 : points
              x = 1
              y = 2

        function declarations
            statics
             basic
                number : 0..10
              defined
                intersect: booleans

        axioms
            function definitions
            intersect if instance(X, 0..30), X = x(p1).

**Comment by Topology** [comment]
There is no output because there is no structure.   There is only a theory.  The theory produces an intermediate sort calculating sparc program which has an answerset.   But the calm.jar only produces the final sparc program if there is a structure.  

I can change this behavior.  I can print out the intermediate sparc program that calculates sorts and its answerset.   Or I can assume an empty structure and translate the remaining fluent axioms.    I just need to know which you would prefer.

**Comment by zhangyuanlin** [comment]
I see. Lets do nothing on this unless you have a reason to change.
